export const phases = [
  {
    id: 0, number: "00", title: "Python Solid", duration: "3–4 أسابيع",
    color: "#00D4FF", glow: "rgba(0,212,255,0.3)", icon: "🐍",
    statusLabel: "✅ خلصته تقريباً",
    topics: [
      { id: "p0_t1", label: "✅ عندك بالفعل", items: [
        { id: "p0_i1", text: "Variables, Loops, Conditions" },
        { id: "p0_i2", text: "Functions & Scope" },
        { id: "p0_i3", text: "NumPy & Pandas أساسيات" },
      ]},
      { id: "p0_t2", label: "🔲 كمّل", items: [
        { id: "p0_i4", text: "OOP كامل (Classes, Inheritance, Dunder methods)" },
        { id: "p0_i5", text: "File Handling + Exception Handling" },
        { id: "p0_i6", text: "List Comprehensions + Generators" },
        { id: "p0_i7", text: "Git & GitHub" },
        { id: "p0_i8", text: "Virtual Environments + pip" },
        { id: "p0_i9", text: "Clean Code Habits (Naming, Structure)" },
      ]},
    ],
    sources: [
      { id: "p0_s1", name: "Elzero Web School — Python", lang: "🇪🇬", type: "يوتيوب", price: "مجاني ✅", note: "عندك — أكمل الباقي", url: "https://www.youtube.com/@ElzeroWebSchool" },
      { id: "p0_s2", name: "CS50P — Harvard", lang: "🌍", type: "كورس", price: "مجاني", note: "الأفضل للـ OOP والـ Clean Code", url: "https://cs50.harvard.edu/python" },
      { id: "p0_s3", name: "Automate the Boring Stuff with Python", lang: "🌍", type: "كتاب / موقع", price: "مجاني", note: "ممتاز للـ OOP والـ Practical Projects", url: "https://automatetheboringstuff.com" },
      { id: "p0_s4", name: "Real Python", lang: "🌍", type: "موقع / مقالات", price: "مجاني جزء منه", note: "مرجع ممتاز للـ Clean Code", url: "https://realpython.com" },
      { id: "p0_s5", name: "Git & GitHub — FreeCodeCamp", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "مهم جداً للـ Portfolio", url: "https://www.youtube.com/watch?v=RGOj5yH7evk" },
      { id: "p0_s6", name: "Python Crash Course — Eric Matthes", lang: "🌍", type: "كتاب", price: "مدفوع", note: "شامل وعملي للمبتدئين", url: "https://nostarch.com/python-crash-course-3rd-edition" },
    ],
  },
  {
    id: 1, number: "01", title: "Math & Data Essentials", duration: "3–4 أسابيع",
    color: "#A78BFA", glow: "rgba(167,139,250,0.3)", icon: "📐",
    topics: [
      { id: "p1_t1", label: "Linear Algebra", items: [
        { id: "p1_i1", text: "Vectors, Matrices, Dot Product" },
        { id: "p1_i2", text: "Matrix Operations & Transpose" },
        { id: "p1_i3", text: "Eigenvalues & SVD (فكرة عامة)" },
      ]},
      { id: "p1_t2", label: "Calculus & Statistics", items: [
        { id: "p1_i4", text: "Derivatives & Partial Derivatives" },
        { id: "p1_i5", text: "Chain Rule (أساس الـ Backprop)" },
        { id: "p1_i6", text: "Mean, Std, Probability Basics" },
        { id: "p1_i7", text: "Bayes Theorem" },
      ]},
      { id: "p1_t3", label: "Data Tools", items: [
        { id: "p1_i8", text: "NumPy (arrays, broadcasting, indexing)" },
        { id: "p1_i9", text: "Pandas (DataFrame, Filtering, GroupBy, Merge)" },
        { id: "p1_i10", text: "Matplotlib & Seaborn (Visualization)" },
      ]},
    ],
    sources: [
      { id: "p1_s1", name: "د. حاتم العطار — Linear Algebra", lang: "🇪🇬", type: "يوتيوب", price: "مجاني ✅", note: "⭐ عندك — الأفضل عربي بعمق", url: "https://youtube.com/@ArtificialIntelligenceDataScie" },
      { id: "p1_s2", name: "د. حاتم العطار — Statistics & Calculus", lang: "🇪🇬", type: "يوتيوب", price: "مجاني ✅", note: "⭐ عندك — المرجع الأساسي", url: "https://youtube.com/@ArtificialIntelligenceDataScie" },
      { id: "p1_s3", name: "3Blue1Brown — Essence of Linear Algebra", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "Visual جداً — الأجمل للـ Math", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2ZAgoSUO7RRMB" },
      { id: "p1_s4", name: "3Blue1Brown — Essence of Calculus", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "نفس الأسلوب البصري الرائع", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr" },
      { id: "p1_s5", name: "StatQuest with Josh Starmer", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "Statistics & ML بأبسط شرح إنجليزي", url: "https://www.youtube.com/@statquest" },
      { id: "p1_s6", name: "Kaggle Learn — Pandas", lang: "🌍", type: "كورس تفاعلي", price: "مجاني", note: "أسرع طريقة للـ Pandas عملياً", url: "https://www.kaggle.com/learn/pandas" },
      { id: "p1_s7", name: "Mathematics for Machine Learning", lang: "🌍", type: "كتاب PDF", price: "مجاني", note: "المرجع الأعمق — للرجوع إليه", url: "https://mml-book.github.io" },
      { id: "p1_s8", name: "Probability Bootcamp — Dr. Steve", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "أحدث كورس Probability عملي — Oct 2024", url: "https://www.youtube.com/playlist?list=PLMrJAkhIeNNR3sNYvfgiKgcStwuPSts9V" },
      { id: "p1_s9", name: "Mathematics for ML — Andrew Ng", lang: "🌍", type: "Coursera", price: "مجاني (audit)", note: "الأشمل للـ Math المطلوب في ML", url: "https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science" },
      { id: "p1_s10", name: "Corey Schafer — Pandas", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "أفضل شرح عملي للـ Pandas", url: "https://www.youtube.com/watch?v=ZyhVh-qRZPA&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS" },
      { id: "p1_s11", name: "NumPy Tutorial — Keith Galli", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "الأفضل للـ NumPy من الصفر", url: "https://www.youtube.com/watch?v=5-5CrLmf2vk&list=PLIA_seGogbkGDYq-dnVCsELEIq_7HK7Ca" },
    ],
  },
  {
    id: 2, number: "02", title: "Classical Machine Learning", duration: "6–8 أسابيع",
    color: "#FB923C", glow: "rgba(251,146,60,0.3)", icon: "⚙️", badge: "أساس قوي",
    topics: [
      { id: "p2_t1", label: "ML Fundamentals", items: [
        { id: "p2_i1", text: "Types: Supervised / Unsupervised / RL" },
        { id: "p2_i2", text: "Train / Validation / Test Split" },
        { id: "p2_i3", text: "Overfitting & Underfitting" },
        { id: "p2_i4", text: "Bias-Variance Tradeoff" },
        { id: "p2_i5", text: "Feature Engineering & Selection" },
        { id: "p2_i6", text: "Data Cleaning & Preprocessing" },
      ]},
      { id: "p2_t2", label: "Supervised Learning", items: [
        { id: "p2_i7", text: "Linear & Polynomial Regression" },
        { id: "p2_i8", text: "Logistic Regression" },
        { id: "p2_i9", text: "Decision Trees & Random Forest" },
        { id: "p2_i10", text: "SVM & KNN" },
        { id: "p2_i11", text: "Gradient Boosting — XGBoost" },
      ]},
      { id: "p2_t3", label: "Unsupervised + Evaluation", items: [
        { id: "p2_i12", text: "K-Means Clustering" },
        { id: "p2_i13", text: "PCA — Dimensionality Reduction" },
        { id: "p2_i14", text: "Accuracy, Precision, Recall, F1" },
        { id: "p2_i15", text: "Confusion Matrix & ROC-AUC" },
        { id: "p2_i16", text: "K-Fold Cross Validation" },
        { id: "p2_i17", text: "Scikit-learn كامل" },
      ]},
    ],
    sources: [
      { id: "p2_s1", name: "د. مصطفى سعد — Classical ML", lang: "🇪🇬", type: "كورس مدفوع", price: "اشتريته ✅", note: "⭐ الأساسي — ابدأ بيه", url: "https://drive.google.com/drive/folders/11prZislvJy0f6vTnd2eWmnCWaF0fJ5m6" },
      { id: "p2_s2", name: "Andrew Ng — ML Specialization", lang: "🌍", type: "Coursera Audit", price: "مجاني ✅", note: "Reference قوي جنب مصطفى سعد", url: "https://www.coursera.org/specializations/machine-learning-introduction" },
      { id: "p2_s3", name: "StatQuest — ML Playlist", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "تعمق في أي Concept محتاجه", url: "https://www.youtube.com/@statquest" },
      { id: "p2_s4", name: "Kaggle Learn — Intro to ML", lang: "🌍", type: "كورس تفاعلي", price: "مجاني", note: "تدريب عملي سريع بعد الكورس", url: "https://www.kaggle.com/learn/intro-to-machine-learning" },
      { id: "p2_s5", name: "Hands-On ML — Aurélien Géron", lang: "🌍", type: "كتاب", price: "مدفوع", note: "الأعمق والأشمل — مرجع أساسي", url: "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/" },
      { id: "p2_s6", name: "Scikit-learn Official Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "مرجع لكل Algorithm وكل Function", url: "https://scikit-learn.org/stable/user_guide.html" },
      { id: "p2_s7", name: "Hesham Asem — ML Arabic", lang: "🇪🇬", type: "يوتيوب", price: "مجاني", note: "Supplement عربي لو محتاج شرح إضافي", url: "https://www.youtube.com/@HeshamAsem" },
      { id: "p2_s8", name: "ML From Scratch — Python Engineer", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "⭐ بناء الـ Algorithms من الصفر بـ Python", url: "https://www.youtube.com/watch?v=ngLyX54e1LU&list=PLqnslRFeH2Upcrywf-u2etjdxxkL8nl7E" },
      { id: "p2_s9", name: "Hands-On ML — الكتاب (3 نسخ مجانية)", lang: "🌍", type: "كتاب PDF", price: "مجاني", note: "الأعمق والأشمل — مرجع أساسي", url: "https://drive.google.com/file/d/11VeqPJw8s9SC9Ru7IVeQhiTwV_9TliOE/view" },
    ],
  },
  {
    id: 3, number: "03", title: "Deep Learning Core", duration: "6–8 أسابيع",
    color: "#34D399", glow: "rgba(52,211,153,0.3)", icon: "🧠",
    topics: [
      { id: "p3_t1", label: "Neural Networks", items: [
        { id: "p3_i1", text: "Perceptron → Multi-layer Perceptron" },
        { id: "p3_i2", text: "Forward Propagation" },
        { id: "p3_i3", text: "Backpropagation & Gradient Descent" },
        { id: "p3_i4", text: "Activation Functions (ReLU, Sigmoid, Softmax)" },
        { id: "p3_i5", text: "Loss Functions (MSE, Cross-Entropy)" },
      ]},
      { id: "p3_t2", label: "PyTorch", items: [
        { id: "p3_i6", text: "Tensors & Autograd" },
        { id: "p3_i7", text: "DataLoader & Dataset" },
        { id: "p3_i8", text: "Building Neural Network من الصفر" },
        { id: "p3_i9", text: "Training Loop كامل" },
        { id: "p3_i10", text: "GPU Training (CUDA)" },
      ]},
      { id: "p3_t3", label: "Architectures", items: [
        { id: "p3_i11", text: "CNNs (Convolution, Pooling, Strides)" },
        { id: "p3_i12", text: "RNNs & LSTMs (فكرة عامة)" },
        { id: "p3_i13", text: "Transfer Learning (ResNet, EfficientNet)" },
        { id: "p3_i14", text: "Image Classification Project كامل" },
        { id: "p3_i15", text: "Attention Mechanism (مقدمة)" },
      ]},
    ],
    sources: [
      { id: "p3_s1", name: "د. مصطفى سعد — Deep Learning Intro", lang: "🇪🇬", type: "كورس مدفوع", price: "اشتريته ✅", note: "⭐ عندك PyTorch + CNN + RNN كامل", url: "https://drive.google.com/drive/folders/11prZislvJy0f6vTnd2eWmnCWaF0fJ5m6" },
      { id: "p3_s2", name: "fast.ai — Practical Deep Learning", lang: "🌍", type: "كورس", price: "مجاني", note: "أفضل Practical Approach بعد مصطفى سعد", url: "https://course.fast.ai" },
      { id: "p3_s3", name: "Andrej Karpathy — Neural Networks Zero to Hero", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "⭐ جوهرة — Backprop بعمق حقيقي", url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ" },
      { id: "p3_s4", name: "Andrew Ng — Deep Learning Specialization", lang: "🌍", type: "Coursera Audit", price: "مجاني", note: "الأعمق نظرياً — كـ Reference", url: "https://www.coursera.org/specializations/deep-learning" },
      { id: "p3_s5", name: "PyTorch Official Tutorials", lang: "🌍", type: "Docs", price: "مجاني", note: "لازم تقراه مع الكورس", url: "https://pytorch.org/tutorials" },
      { id: "p3_s6", name: "Deep Learning Book — Goodfellow et al.", lang: "🌍", type: "كتاب PDF", price: "مجاني", note: "المرجع النظري الأعمق في الـ DL", url: "https://www.deeplearningbook.org" },
      { id: "p3_s7", name: "d2l.ai — Dive into Deep Learning", lang: "🌍", type: "كتاب تفاعلي", price: "مجاني", note: "كود + نظرية + تمارين — ممتاز", url: "https://d2l.ai" },
      { id: "p3_s8", name: "MIT — Intro to Deep Learning", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "⭐ محدّث سنوياً — الأفضل للـ DL foundations", url: "http://introtodeeplearning.com" },
      { id: "p3_s9", name: "Deep Learning — UC Berkeley", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "شامل جداً مع exercises", url: "https://www.youtube.com/playlist?list=PLZSO_6-bSqHQHBCoGaObUljoXAyyqhpFW" },
    ],
  },
  {
    id: 4, number: "04", title: "Computer Vision", duration: "6–8 أسابيع",
    color: "#F472B6", glow: "rgba(244,114,182,0.3)", icon: "👁️", badge: "تخصصك ⭐",
    topics: [
      { id: "p4_t1", label: "OpenCV", items: [
        { id: "p4_i1", text: "Image Read, Write, Display" },
        { id: "p4_i2", text: "Color Spaces (BGR, RGB, HSV)" },
        { id: "p4_i3", text: "Filters, Edge Detection (Canny, Sobel)" },
        { id: "p4_i4", text: "Contours & Morphological Operations" },
        { id: "p4_i5", text: "Video Processing Frame by Frame" },
      ]},
      { id: "p4_t2", label: "Modern CV Models", items: [
        { id: "p4_i6", text: "YOLO — Object Detection (v8/v11)" },
        { id: "p4_i7", text: "SAM — Segment Anything Model" },
        { id: "p4_i8", text: "CLIP — Image + Text Understanding" },
        { id: "p4_i9", text: "Vision Transformers (ViT)" },
        { id: "p4_i10", text: "Depth Estimation Models" },
      ]},
      { id: "p4_t3", label: "Generative Image AI", items: [
        { id: "p4_i11", text: "GANs (فكرة عامة)" },
        { id: "p4_i12", text: "Diffusion Models — كيف تشتغل" },
        { id: "p4_i13", text: "Stable Diffusion / ComfyUI" },
        { id: "p4_i14", text: "Image Generation APIs (DALL-E, Midjourney)" },
        { id: "p4_i15", text: "ControlNet & Image-to-Image" },
      ]},
    ],
    sources: [
      { id: "p4_s1", name: "PyImageSearch — OpenCV Tutorials", lang: "🌍", type: "موقع / مقالات", price: "مجاني جزء منه", note: "⭐ المرجع الأول للـ OpenCV", url: "https://pyimagesearch.com" },
      { id: "p4_s2", name: "OpenCV Official Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "المرجع الرسمي لكل Function", url: "https://docs.opencv.org/4.x/d9/df8/tutorial_root.html" },
      { id: "p4_s3", name: "Ultralytics YOLO Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "أسرع طريقة تشغّل YOLO", url: "https://docs.ultralytics.com" },
      { id: "p4_s4", name: "HuggingFace — Computer Vision Course", lang: "🌍", type: "كورس", price: "مجاني", note: "⭐ ViT + CLIP + SAM بعمق", url: "https://huggingface.co/learn/computer-vision-course" },
      { id: "p4_s5", name: "Roboflow — CV Tutorials & Projects", lang: "🌍", type: "موقع", price: "مجاني", note: "Projects حقيقية + Datasets جاهزة", url: "https://roboflow.com/learn" },
      { id: "p4_s6", name: "fast.ai — CV Part", lang: "🌍", type: "كورس", price: "مجاني", note: "تطبيقي رائع على الـ CV", url: "https://course.fast.ai" },
      { id: "p4_s7", name: "Programming Computer Vision — Jan Solem", lang: "🌍", type: "كتاب PDF", price: "مجاني", note: "كتاب كلاسيكي للـ CV الأساسيات", url: "http://programmingcomputervision.com" },
      { id: "p4_s8", name: "Practical Deep Learning for CV — O'Reilly", lang: "🌍", type: "كتاب", price: "مدفوع", note: "أشمل كتاب CV عملي حديث", url: "https://www.oreilly.com/library/view/practical-deep-learning/9781492034858/" },
      { id: "p4_s9", name: "Deep Learning for CV — Michigan", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "⭐ الأفضل لـ CV بعمق — University of Michigan", url: "https://www.youtube.com/playlist?list=PL5-TkQAfAZFbzxjBHtzdVCWE0Zbhomg7r" },
      { id: "p4_s10", name: "Modern CV — UC Berkeley CS198", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "أحدث تقنيات الـ CV — Fall 2022", url: "https://www.youtube.com/playlist?list=PLzWRmD0Vi2KVsrCqA4VnztE4t71KnTnP5" },
    ],
  },
  {
    id: 5, number: "05", title: "AI Engineer Layer", duration: "4–6 أسابيع",
    color: "#FBBF24", glow: "rgba(251,191,36,0.3)", icon: "🤖",
    topics: [
      { id: "p5_t1", label: "HuggingFace Ecosystem", items: [
        { id: "p5_i1", text: "Models Hub & Pipelines" },
        { id: "p5_i2", text: "Transformers Library" },
        { id: "p5_i3", text: "Tokenizers & Feature Extractors" },
        { id: "p5_i4", text: "HuggingFace Spaces (نشر Projects)" },
        { id: "p5_i5", text: "Fine-tuning Pre-trained Models" },
      ]},
      { id: "p5_t2", label: "Multimodal AI", items: [
        { id: "p5_i6", text: "Image + Text Models (GPT-4V, Gemini Vision)" },
        { id: "p5_i7", text: "Video Understanding APIs" },
        { id: "p5_i8", text: "Whisper — Speech-to-Text" },
        { id: "p5_i9", text: "Text-to-Image APIs (DALL-E, Stability AI)" },
        { id: "p5_i10", text: "LangChain للـ Multimodal Apps" },
      ]},
      { id: "p5_t3", label: "Embeddings & Vector Search", items: [
        { id: "p5_i11", text: "ما هي الـ Embeddings وكيف تشتغل" },
        { id: "p5_i12", text: "Semantic Image Search" },
        { id: "p5_i13", text: "FAISS / Chroma DB" },
        { id: "p5_i14", text: "RAG — Retrieval Augmented Generation (فكرة)" },
      ]},
    ],
    sources: [
      { id: "p5_s1", name: "HuggingFace — Transformers Course", lang: "🌍", type: "كورس", price: "مجاني", note: "⭐ الأفضل للـ Transformers Ecosystem", url: "https://huggingface.co/learn/nlp-course" },
      { id: "p5_s2", name: "HuggingFace — Computer Vision Course", lang: "🌍", type: "كورس", price: "مجاني", note: "Multimodal AI + Vision Transformers", url: "https://huggingface.co/learn/computer-vision-course" },
      { id: "p5_s3", name: "OpenAI API Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "Vision API + Whisper + DALL-E + Embeddings", url: "https://platform.openai.com/docs" },
      { id: "p5_s4", name: "Andrej Karpathy — YouTube Channel", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "⭐ أعمق فهم لـ LLMs وراء الـ API", url: "https://www.youtube.com/@AndrejKarpathy" },
      { id: "p5_s5", name: "LangChain Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "للـ Chains + RAG + Multimodal Apps", url: "https://python.langchain.com/docs" },
      { id: "p5_s6", name: "roadmap.sh — AI Engineer", lang: "🌍", type: "موقع", price: "مجاني", note: "مرجع تفاعلي لكل المسار", url: "https://roadmap.sh/ai-engineer" },
      { id: "p5_s7", name: "LLM Bootcamp — Full Stack Deep Learning", lang: "🌍", type: "كورس", price: "مجاني", note: "⭐ RAG + Agents + LLMOps كاملين", url: "https://fullstackdeeplearning.com/llm-bootcamp/spring-2023/" },
      { id: "p5_s8", name: "Moataz Elmesmary — DS Roadmap Resources", lang: "🇪🇬", type: "GitHub", price: "مجاني", note: "مجموعة ضخمة من المصادر المنظمة", url: "https://github.com/Moataz-Elmesmary/Data-Science-Roadmap" },
    ],
  },
  {
    id: 6, number: "06", title: "Build & Deploy", duration: "4 أسابيع",
    color: "#F87171", glow: "rgba(248,113,113,0.3)", icon: "🚀", badge: "Portfolio",
    topics: [
      { id: "p6_t1", label: "Building Apps", items: [
        { id: "p6_i1", text: "Gradio — أسرع AI App" },
        { id: "p6_i2", text: "Streamlit — Data Apps" },
        { id: "p6_i3", text: "FastAPI للـ Backend & REST API" },
        { id: "p6_i4", text: "Frontend أساسي (HTML/CSS — اختياري)" },
      ]},
      { id: "p6_t2", label: "Deployment & MLOps", items: [
        { id: "p6_i5", text: "Docker — Containerization أساسيات" },
        { id: "p6_i6", text: "HuggingFace Spaces (Deploy مجاناً)" },
        { id: "p6_i7", text: "Google Colab Pro للـ Training" },
        { id: "p6_i8", text: "Model Versioning & Experiment Tracking (MLflow)" },
        { id: "p6_i9", text: "CI/CD أساسيات (GitHub Actions)" },
      ]},
      { id: "p6_t3", label: "Portfolio Projects", items: [
        { id: "p6_i10", text: "Project 1: Real-time Object Detection App" },
        { id: "p6_i11", text: "Project 2: Image Generation / Style Transfer App" },
        { id: "p6_i12", text: "Project 3: Multimodal AI App (Image + Text)" },
        { id: "p6_i13", text: "GitHub Profile + README لكل Project" },
        { id: "p6_i14", text: "LinkedIn Profile محدّث" },
      ]},
    ],
    sources: [
      { id: "p6_s1", name: "Gradio Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "⭐ AI App في 10 دقايق", url: "https://www.gradio.app/guides" },
      { id: "p6_s2", name: "FastAPI Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "أوضح Docs للـ Backend", url: "https://fastapi.tiangolo.com" },
      { id: "p6_s3", name: "Streamlit Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "Data Apps بسرعة", url: "https://docs.streamlit.io" },
      { id: "p6_s4", name: "HuggingFace Spaces Guide", lang: "🌍", type: "Docs", price: "مجاني", note: "Deploy مجاناً للـ Projects", url: "https://huggingface.co/docs/hub/spaces" },
      { id: "p6_s5", name: "TechWithTim — FastAPI + Docker", lang: "🌍", type: "يوتيوب", price: "مجاني", note: "Docker + FastAPI عملي خطوة بخطوة", url: "https://www.youtube.com/@TechWithTim" },
      { id: "p6_s6", name: "Docker Official Docs — Get Started", lang: "🌍", type: "Docs", price: "مجاني", note: "لازم تفهم Docker من المصدر", url: "https://docs.docker.com/get-started/" },
      { id: "p6_s7", name: "MLflow Docs", lang: "🌍", type: "Docs", price: "مجاني", note: "Experiment Tracking للـ Models", url: "https://mlflow.org/docs/latest/index.html" },
    ],
  },
];

export const transferable = [
  { skill: "PyTorch", goes: "NLP, RL, Any DL" },
  { skill: "Transformers", goes: "BERT, GPT, كل حاجة" },
  { skill: "HuggingFace", goes: "NLP Models جاهزة" },
  { skill: "Git + Clean Code", goes: "أي تراك" },
  { skill: "Embeddings", goes: "NLP, Search, Agents" },
  { skill: "FastAPI + Deploy", goes: "أي Product" },
];
